export const uxCopy = {
  disclaimer: {
    key: 'ccc-shell-disclaimer-v1',
    sessionKey: 'ccc-shell-disclaimer-session-v1',
    text: 'Heads up: this is playful copy for planning only, not legal advice.',
    dismissCta: 'Got it',
    footnote: 'Satire mode is optional. Real legal promises still require real paperwork.',
  },
  legal: {
    footerLabel: '© 2026 ICEA · Camel equivalents for fun planning.',
    links: [
      { href: '/fine-print', label: 'Privacy Policy' },
      { href: '/privacy-theater', label: 'Terms' },
      { href: '/terms-of-camelage', label: 'Disclaimers' },
    ],
    mobileFootnoteSummary: 'More legal-ish notes',
    mobileFootnote: 'Filed under Article 404: Seriousness Not Found.',
  },
  loadingFacts: [
    'Did you know? Camels can drink 30 gallons in 13 minutes—faster than your ex.',
    'Footnote: Camels not included; bring your own hump.',
    'Archive delay notice: one clerk is polishing an imaginary gold seal.',
  ],
  phases: {
    phase1: {
      heading: 'Who’s the lucky one?',
      subtitle: 'Add the basics so we can estimate a fair camel equivalent.',
      cta: 'See my estimate',
      secondaryCta: 'Clear optional details',
      advancedLabel: 'Optional declarations',
      labels: {
        bidName: 'Full Legal Name *',
        bidRegion: 'Jurisdictional Territory *',
        camelQuantity: 'Baseline Camel Bid',
        warriorStatus: 'Warrior credentials (optional)',
        hobby: 'Primary avocation (optional)',
        courtshipYears: 'Courtship duration (optional)',
        artifact: 'Custodian of enchanted relics (optional)',
        quirks: 'Supplementary particulars (optional)',
      },
      placeholders: {
        bidName: 'e.g. Sir Lancelot du Lac',
        bidRegion: 'Select jurisdiction',
        hobby: 'e.g. Arcane sorcery',
        quirks: 'Limit 140 characters for archival purposes',
      },
      helper: {
        requiredFields: '* Mandatory for enforceability under Statute 1.0.',
        quantityRange: (min: number, max: number) => `Permissible filing range: ${min}–${max} camels.`,
        examples: 'Examples accepted by the clerk: 2 camels, 5 yaks, 2 cows.',
      },
    },
    phase2: {
      heading: 'How does this offer compare?',
      subtitle: 'Review the estimate, tweak settings, and pick your best match.',
      advancedLabel: 'Adjustment controls',
      cta: 'Save this estimate',
      secondaryCta: 'Reset to my original bid',
      noResult: 'No estimate yet. Start with the first step.',
      compareCta: 'Compare options',
    },
    phase3: {
      heading: 'Ready to draft your agreement?',
      subtitle: 'Edit the draft text and finalize when it looks right.',
      cta: 'Finish and open docket',
    },
    phase4: {
      heading: 'Need to review past offers?',
      subtitle: 'Check saved entries, then start a new one anytime.',
      cta: 'Save to archive',
      primaryCta: 'Start a new offer',
      empty: 'No sealed bid on record yet.',
    },
  },
  errors: {
    defaultStatute: 'Statute 0',
    parseUnknown: "Invalid Declaration: Filing is indecipherable. Try '2 camels' or '5 yaks'. (Statute 1.3)",
    proxyNotFound: (proxyName: string) => `Invalid Declaration: '${proxyName}' is not a recognized proxy witness. (Statute 12.b)`,
    calculationFailed: 'Invalid Declaration: Valuation could not be computed. (Statute 3.14)',
    compareFailed: 'Invalid Declaration: Comparative hearing failed; review selected proxies. (Statute 7.0)',
    formalizerFailed: 'Invalid Declaration: Instrument drafting did not complete. (Statute 9.0)',
    exportFailed: 'Invalid Declaration: Seal application denied. (Statute 11.0)',
    archiveFailed: 'Invalid Declaration: Archive registrar refused entry. (Statute 15.0)',
    createProxyFailed: 'Invalid Declaration: Proxy petition rejected; provide valid evidence. (Statute 5.0)',
  },
} as const;
