export const uxCopy = {
  disclaimer: {
    key: 'ccc-shell-disclaimer-v1',
    sessionKey: 'ccc-shell-disclaimer-session-v1',
    text: 'Heads up: this is playful copy for planning only, not legal advice.',
    dismissCta: 'Got it',
    footnote: 'Satire mode is optional. Real legal promises still require real paperwork.',
  },
  legal: {
    footerLabel: '© 2026 ICEA · Camel equivalents for fun planning.',
    links: [
      { href: '/fine-print', label: 'Privacy Policy' },
      { href: '/privacy-theater', label: 'Terms' },
      { href: '/terms-of-camelage', label: 'Disclaimers' },
    ],
    mobileFootnoteSummary: 'More legal-ish notes',
    mobileFootnote: 'Filed under Article 404: Seriousness Not Found.',
  },
  loadingFacts: [
    'Did you know? Camels can drink 30 gallons in 13 minutes—faster than your ex.',
    'Footnote: Camels not included; bring your own hump.',
    'Archive delay notice: one clerk is polishing an imaginary gold seal.',
  ],
  phases: {
    phase1: {
      heading: 'Start your proposal',
      subtitle: 'Who is this for? Add the basics and we will suggest an equivalent.',
      cta: 'Next: see estimate',
      secondaryCta: 'Clear optional details',
      advancedLabel: 'Optional details',
      labels: {
        bidName: 'Their name *',
        bidRegion: 'Where are they from? *',
        camelQuantity: 'Opening camel offer',
        warriorStatus: 'Warrior skills',
        hobby: 'Hobby',
        courtshipYears: 'Years together',
        artifact: 'Ceremonial artifact',
        quirks: 'Extra notes',
      },
      placeholders: {
        bidName: 'e.g. Alex',
        bidRegion: 'Select region',
        hobby: 'e.g. Falconry',
        quirks: 'Optional context for your draft',
      },
      helper: {
        requiredFields: '* Required to continue.',
        quantityRange: (min: number, max: number) => `Range: ${min}–${max} camels.`,
        examples: 'Examples: 2 camels, 5 yaks, 2 cows.',
      },
    },
    phase2: {
      heading: 'Suggested equivalent',
      subtitle: 'Looks good? Lock it in. Need tweaks? Open details.',
      advancedLabel: 'Adjustment controls',
      cta: 'Looks good, lock it in',
      secondaryCta: 'Reset to original bid',
      noResult: 'No estimate yet. Start with card 1.',
      compareCta: 'Compare options',
    },
    phase3: {
      heading: 'Your official proposal',
      subtitle: 'Edit, copy, or download your draft when ready.',
      cta: 'Done: open queue',
    },
    phase4: {
      heading: 'Your proposals',
      subtitle: 'Review saved entries or start a new one.',
      cta: 'Save to archive',
      primaryCta: 'New proposal',
      empty: 'No sealed bid on record yet.',
    },
  },
  errors: {
    defaultStatute: 'Statute 0',
    parseUnknown: "Invalid Declaration: Filing is indecipherable. Try '2 camels' or '5 yaks'. (Statute 1.3)",
    proxyNotFound: (proxyName: string) => `Invalid Declaration: '${proxyName}' is not a recognized proxy witness. (Statute 12.b)`,
    calculationFailed: 'Invalid Declaration: Valuation could not be computed. (Statute 3.14)',
    compareFailed: 'Invalid Declaration: Comparative hearing failed; review selected proxies. (Statute 7.0)',
    formalizerFailed: 'Invalid Declaration: Instrument drafting did not complete. (Statute 9.0)',
    exportFailed: 'Invalid Declaration: Seal application denied. (Statute 11.0)',
    archiveFailed: 'Invalid Declaration: Archive registrar refused entry. (Statute 15.0)',
    createProxyFailed: 'Invalid Declaration: Proxy petition rejected; provide valid evidence. (Statute 5.0)',
  },
} as const;
