export const uxCopy = {
  global: {
    appTitle: 'Dowry Proposal Advisory',
    persistentDisclaimer: 'DBT advisory instrument. No enforceability implied.',
    footer: 'DBT Rates as of February 22, 2026. All bids advisory only.',
    startOver: 'Start over',
  },
  page1: {
    title: 'Dowry Proposal Advisory Service',
    body: [
      'Utilize our Definitive Benchmarking Tool to formalize a dowry bid in certified proxies.',
      'Select from unhinged alternatives to camels for a binding-ish proposal.',
      'Proceed for advisory computation.',
    ],
    begin: 'Begin Advisory Process',
    howItWorksLabel: 'How this works',
    howItWorksText: 'Complete profile basics, lock a proxy bid using DBT live rates, and generate an advisory contract docket entry.',
    footnotes: [
      '*Pursuant to DBT v2.026, all opening statements are ceremonial and non-binding.',
      '*Certified Absurd Exchange protocols prohibit last-minute conversion to sensible assets.',
    ],
  },
  page2: {
    title: 'Subject Profile (Advisory Intake Docket)',
    nameLabel: 'Name*',
    namePlaceholder: 'e.g., Jordan Lee, collector of goblin gadgets',
    regionLabel: 'Region*',
    regionPlaceholder: 'Select a region',
    addMore: 'Add Particulars?',
    hideMore: 'Hide particulars',
    ageRange: 'Age Bracket',
    occupation: 'Vocation',
    occupationPlaceholder: 'e.g., Analyst of ceremonial yak futures',
    quirkyFact: 'Anecdotal Note',
    quirkyFactPlaceholder: 'e.g., maintains a licensed sentient sandwich shelf',
    continue: 'Proceed to Bid Library',
    footnotes: [
      '*Advisory intake fields are archived under Bureau of Absurd Exchanges retention doctrine.',
    ],
  },
  page3: {
    title: 'Select Bid Proxy & Amount (DBT v2.026)',
    suggestion: (name: string) => `Selected Proxy: ${name || 'None selected yet'}`,
    helper: 'Reference the DBT for live translation rates. Rates fluctuate per advisory index.',
    live: (camelEquivalent: number) => `Current Benchmark: ≈ ${camelEquivalent} camels`,
    lockIn: 'Lock Advisory Bid',
    footnote: 'DBT rates sourced from the Bureau of Absurd Exchanges. Non-refundable.',
    browse: 'Browse Full DBT Library',
    searchPlaceholder: 'Search proxies',
    formula: (qty: number, rate: number, camels: number, vol: number) => `DBT Computation: ${qty} × ${rate} = ${camels} Camel Equivalent (Volatility: +${vol}% today).`,
    empty: 'No proxies match this filter.',
    volatilityAlert: (vol: number) => `Volatility Alert: +${vol}% (Yak Futures Dip).`,
    footnotes: [
      '*DBT disclaims liability for exploding toads, unstable quokkas, and ceremonial yippy dog logistics.',
      '*Certified Absurd Exchange rates refresh daily and mature with dignity regardless of outcomes.',
    ],
  },
  page4: {
    title: 'Advisory Proposal Contract (Indenture Preview)',
    personalizeLabel: 'Enhance Contract?',
    customSentence: 'Addendum Clause',
    tone: 'Tone Adjust',
    done: 'Conclude & Access Docket',
    copy: 'Copy Contract',
    downloadTxt: 'Download .txt',
    downloadPdf: 'Download PDF',
    share: 'Transmit Advisory',
    clauseLabel: 'Preset clause',
    generate: 'Generate / Refresh contract',
    editWarning: 'Advisory Warning: altering clauses may void DBT certification.',
    footnotes: [
      '*Clause amendments are logged pursuant to DBT statute 3.14 and archived for dramatic effect.',
    ],
  },
  page5: {
    title: 'Advisory Docket',
    empty: 'No advisory indentures recorded yet.',
    startNew: 'New Advisory Process',
    view: 'View',
    copy: 'Share',
    share: 'Transmit',
    delete: 'Delete',
    extras: 'Further Advisory Tools',
    unlock: 'New Advisory Tools Available',
    localNote: 'Side tools for enhanced advisory absurdity. DBT disclaims all yak futures.',
    footnotes: [
      '*This indenture has matured under Bureau review; minor volatility drift is expected.',
    ],
  },
  disclaimer: {
    key: 'legacy-disclaimer-key',
    sessionKey: 'legacy-disclaimer-session',
    text: 'For entertainment purposes only. Not legal advice.',
    dismissCta: 'Dismiss',
    footnote: 'Parody text only.',
  },
  legal: {
    footerLabel: 'This is a parody tool. Not legal advice. No actual dowries exchanged.',
    links: [],
    mobileFootnoteSummary: 'Note',
    mobileFootnote: 'For entertainment purposes only.',
  },
  phases: {
    phase1: { heading: '', subtitle: '', cta: '', secondaryCta: '', advancedLabel: '', labels: { bidName: '', bidRegion: '', camelQuantity: '', warriorStatus: '', hobby: '', courtshipYears: '', artifact: '', quirks: '' }, placeholders: { bidName: '', bidRegion: '', hobby: '', quirks: '' }, helper: { requiredFields: '', quantityRange: (_min: number, _max: number) => '', examples: '' } },
    phase2: { heading: '', subtitle: '', advancedLabel: '', cta: '', secondaryCta: '', noResult: '', compareCta: '' },
    phase3: { heading: '', subtitle: '', cta: '' },
    phase4: { heading: '', subtitle: '', cta: '', primaryCta: '', empty: '' },
  },
  loadingFacts: [],
  errors: {
    nameRequired: 'Invalid Entry: Per DBT Statute 1.01, please enter a name.',
    regionRequired: 'Invalid Entry: Per DBT Statute 1.02, please select a region.',
    proposalRequired: 'Please generate a contract first.',
    proxyRequired: 'Invalid Entry: Per DBT Statute 3.14, quantities must exceed zero yippy dogs and include a selected proxy.',
    defaultStatute: 'Notice',
    parseUnknown: 'Please enter a valid value.',
    proxyNotFound: (proxyName: string) => `${proxyName} is not a recognized option.`,
    calculationFailed: 'Calculation failed.',
    compareFailed: 'Comparison failed.',
    formalizerFailed: 'Message generation failed.',
    exportFailed: 'Export failed.',
    archiveFailed: 'Archive failed.',
    createProxyFailed: 'Could not create item.',
  },
} as const;
